print("   /|")
print("  / |")
print(" /  |")
print("/___|")
# character_name="Vaish "
# age="24"
# print("Her name is "+ character_name + "and she is " + age + " years old")
# print("Vaishnavi \" Python")
# phrase="Vaish"
# print(phrase.islower())
# print(phrase.upper().isupper())
# print(len(phrase))
# print(phrase[0])
# print(phrase.index("aish"))
# print(phrase.replace("Vaish", "Adora"))
# print(3*(4+5))
# my_num=-5
# print(my_num)
# print(str(my_num) + " is my fav number")
# print(abs(my_num))
# print(pow(2,3))
# my_num=(1,2,3)
# print(round(4.3))
# from math import *
# print(floor(3.7))
# print(ceil(3.7))
# print(sqrt(36))
# name = input("Enter your name: ")
# age = input("Enter your age: ")
# print("Hello " + name + " You are " + age)
# num1= input("Enter a number:")
# num2= input("Enter another number:")
# result= float(num1) + float(num2)
# print(result)
# color=input("enter a color :")
# plural_noun=input("enter a plural noun :")
# celebrity=input("enter a celebrity :")
# print("Roses are" + color)
# print(plural_noun + " are blue")
# print("I love " + celebrity)
# lucky_num=[4,22,197,76,11]
# friends= ["Sneha", "Varsha", "Meghs", "Teja"]
# print(friends.index("Meghs"))
# print(friends[0])
# print(friends[1:])
# print(friends[1:3])
# friends[1] = "Tanya"
# print(friends)
# lucky_num=[4,22,197,76,11]
# friends= ["Sneha", "Varsha", "Meghs", "Teja"]
# college= ["Tanya", "Sindhu"]
# friends.extend(college)
# friends.append("Vaish")
# friends.insert(1, "Vaish")
# friends.remove("Sneha")
# friends.clear()
# friends.pop()
# print(friends)
# print(friends.index("Teja"))
# friends= ["Sneha", "Varsha", "Meghs", "Teja"]
# print(friends.count("Meghs"))
# friends.sort()
# friends.reverse()
# friends2= friends.copy()
# print(friends2)
